### ISSUE TITLE
RingScreen question

### ISSUE THREAD

**Issue by jamesdalg** [mhayes20/RingScreen#1]
Did this project ever come to work out? I'd be interested to try it out on my data.

**Comment by mhayes20** [comment]
Thanks for your interest. Unfortunately the original code was lost due to unforeseen circumstances, but I am considering revisiting the project since there still isn't much out there in terms of software for chromosome ring discovery.

**Comment by jamesdalg** [comment]
Good to know. I've looked into both your DMFinder and your newest package https://github.com/mhayes20/HolistIC. We don't have any Hi-C data on the samples in question (the tumor samples were sequenced long ago). If you have any new tools, I'd definitely like to try them. I've tried DMFinder in the past, but it wasn't sensitive for our samples (which tend to have a lot of chromothripsis and co-occurring events).
